# Generated by Django 4.2.10 on 2024-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0002_company_customerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
