# Generated by Django 4.2.10 on 2024-03-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0005_alter_company_picture_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
