# Generated by Django 4.2.10 on 2024-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0006_rename_address_userprofile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('picture', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='types_of_garbage',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
