# Generated by Django 4.2.10 on 2024-03-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0008_delete_garbagecollectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
