# Generated by Django 4.2.10 on 2024-03-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0009_alter_company_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='background_image',
            field=models.ImageField(default='yange.jpg', upload_to='static/images'),
        ),
    ]
