# Generated by Django 4.2.10 on 2024-05-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0015_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='map_url',
            field=models.URLField(blank=True),
        ),
    ]
