# Generated by Django 4.2.10 on 2024-05-10 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0016_company_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a 10-digit phone number.')]),
        ),
    ]
