# Generated by Django 5.0.6 on 2024-05-28 07:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0017_alter_customerrequest_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_system.district'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_system.street'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_system.ward'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a 10-digit phone number.')]),
        ),
    ]
