# Generated by Django 5.0.6 on 2024-05-28 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0018_remove_customerrequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
