# Generated by Django 5.0.6 on 2024-06-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0019_customerrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='map_url',
        ),
    ]
