# Generated by Django 5.0.6 on 2024-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0020_remove_company_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_option', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='types_of_garbage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
