# Generated by Django 5.0.6 on 2024-06-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_system', '0023_alter_customerrequest_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
